// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5bbZn0WeGxn0G6Al3IyI2pGZMrmtRgS8',
    appId: '1:524355519286:web:b0e25b465c74072d8ca997',
    messagingSenderId: '524355519286',
    projectId: 'gsc-swatify',
    authDomain: 'gsc-swatify.firebaseapp.com',
    storageBucket: 'gsc-swatify.firebasestorage.app',
    measurementId: 'G-J9MMS2ZCRC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA4A2qi5b_f9qQmshAbn1U-GY8AS_B6j0',
    appId: '1:524355519286:android:957379efaa622a358ca997',
    messagingSenderId: '524355519286',
    projectId: 'gsc-swatify',
    storageBucket: 'gsc-swatify.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn_HEkjx7HzUSd78aggeJSImzGFiMLmWw',
    appId: '1:524355519286:ios:a06e5ad4ed27c8e48ca997',
    messagingSenderId: '524355519286',
    projectId: 'gsc-swatify',
    storageBucket: 'gsc-swatify.firebasestorage.app',
    androidClientId: '524355519286-8si57iqtohch1pqv1j1t1r8in8o4pk2v.apps.googleusercontent.com',
    iosClientId: '524355519286-i1hqdmf7g5pjaflrkqok69ndk3eb420i.apps.googleusercontent.com',
    iosBundleId: 'com.example.swastify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn_HEkjx7HzUSd78aggeJSImzGFiMLmWw',
    appId: '1:524355519286:ios:a06e5ad4ed27c8e48ca997',
    messagingSenderId: '524355519286',
    projectId: 'gsc-swatify',
    storageBucket: 'gsc-swatify.firebasestorage.app',
    androidClientId: '524355519286-8si57iqtohch1pqv1j1t1r8in8o4pk2v.apps.googleusercontent.com',
    iosClientId: '524355519286-i1hqdmf7g5pjaflrkqok69ndk3eb420i.apps.googleusercontent.com',
    iosBundleId: 'com.example.swastify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5bbZn0WeGxn0G6Al3IyI2pGZMrmtRgS8',
    appId: '1:524355519286:web:9878b1930b31123b8ca997',
    messagingSenderId: '524355519286',
    projectId: 'gsc-swatify',
    authDomain: 'gsc-swatify.firebaseapp.com',
    storageBucket: 'gsc-swatify.firebasestorage.app',
    measurementId: 'G-9L8TJYMWGM',
  );
}
